### ISSUE TITLE
Bad Query: SELECT "id","type" FROM "public"."roles" WHERE "id"$1 LIMIT 

### ISSUE THREAD

**Issue by slively** [strongloop/loopback-connector-postgresql#106]
It looks like the WHERE clause is missing an '=' somehow.

Postgres query:
SELECT "id","type" FROM "public"."roles" WHERE "id"$1 LIMIT

This is the REST API queries where this happens:
DELETE http://localhost:3000/api/Users/32/roles/rel/2
PUT http://localhost:3000/api/Users/32/roles/rel/2

These REST API queries works just fine:
HEAD http://localhost:3000/api/Users/32/roles/rel/2
GET http://localhost:3000/api/Users/32/roles/rel/2

Models:

```
{
  "name": "Roles",
  "idInjection": false,
  "postgresql": {
    "schema": "public",
    "table": "roles"
  },
  "properties": {
    "id": {
      "id": true,
      "type": "Number",
      "required": false,
      "length": null,
      "precision": 32,
      "scale": 0,
      "postgresql": {
        "columnName": "id",
        "dataType": "integer",
        "dataLength": null,
        "dataPrecision": 32,
        "dataScale": 0,
        "nullable": "NO"
      }
    },
    "type": {
      "type": "String",
      "required": false,
      "length": 40,
      "precision": null,
      "scale": null,
      "postgresql": {
        "columnName": "type",
        "dataType": "character varying",
        "dataLength": 40,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "YES"
      }
    }
  },
  "validations": [],
  "relations": {
      "users": {
          "type": "hasMany",
          "model": "Users",
          "foreignKey": "roleId",
          "through": "RolesUsers"
      }
  },
  "acls": [],
  "methods": []
}


{
  "name": "RolesUsers",
  "idInjection": false,
  "postgresql": {
    "schema": "public",
    "table": "roles_users"
  },
  "properties": {
    "id": {
      "id": true,
      "type": "Number",
      "required": false,
      "length": null,
      "precision": 32,
      "scale": 0,
      "postgresql": {
        "columnName": "id",
        "dataType": "integer",
        "dataLength": null,
        "dataPrecision": 32,
        "dataScale": 0,
        "nullable": "NO"
      }
    },
    "userId": {
      "type": "Number",
      "required": false,
      "length": null,
      "precision": 32,
      "scale": 0,
      "postgresql": {
        "columnName": "user_id",
        "dataType": "integer",
        "dataLength": null,
        "dataPrecision": 32,
        "dataScale": 0,
        "nullable": "YES"
      }
    },
    "roleId": {
      "type": "Number",
      "required": false,
      "length": null,
      "precision": 32,
      "scale": 0,
      "postgresql": {
        "columnName": "role_id",
        "dataType": "integer",
        "dataLength": null,
        "dataPrecision": 32,
        "dataScale": 0,
        "nullable": "YES"
      }
    }
  },
  "validations": [],
  "relations": {
      "users": {
          "type": "belongsTo",
          "model": "Users",
          "foreignKey": "userId"
      },
      "roles": {
          "type": "belongsTo",
          "model": "Roles",
          "foreignKey": "roleId"
      }
  },
  "acls": [],
  "methods": []
}


{
  "name": "Users",
  "idInjection": false,
  "postgresql": {
    "schema": "public",
    "table": "users"
  },
  "properties": {
    "id": {
      "id": true,
      "type": "Number",
      "required": false,
      "length": null,
      "precision": 32,
      "scale": 0,
      "postgresql": {
        "columnName": "id",
        "dataType": "integer",
        "dataLength": null,
        "dataPrecision": 32,
        "dataScale": 0,
        "nullable": "NO"
      }
    },
    "fName": {
      "type": "String",
      "required": true,
      "length": 40,
      "precision": null,
      "scale": null,
      "postgresql": {
        "columnName": "f_name",
        "dataType": "character varying",
        "dataLength": 40,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "NO"
      }
    },
    "lName": {
      "type": "String",
      "required": true,
      "length": 40,
      "precision": null,
      "scale": null,
      "postgresql": {
        "columnName": "l_name",
        "dataType": "character varying",
        "dataLength": 40,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "NO"
      }
    },
    "username": {
      "type": "String",
      "required": true,
      "length": 40,
      "precision": null,
      "scale": null,
      "postgresql": {
        "columnName": "username",
        "dataType": "character varying",
        "dataLength": 40,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "NO"
      }
    },
    "emailAddress": {
      "type": "String",
      "required": true,
      "length": 40,
      "precision": null,
      "scale": null,
      "postgresql": {
        "columnName": "email_address",
        "dataType": "character varying",
        "dataLength": 40,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "YES"
      }
    },
    "approved": {
      "type": "Boolean",
      "required": true,
      "length": null,
      "precision": null,
      "scale": null,
      "postgresql": {
        "columnName": "approved",
        "dataType": "boolean",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "NO"
      }
    },
    "timeCreated": {
      "type": "Date",
      "required": false,
      "length": null,
      "precision": null,
      "scale": null,
      "postgresql": {
        "columnName": "time_created",
        "dataType": "date",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "NO"
      }
    },
    "dateModified": {
      "type": "Date",
      "required": false,
      "length": null,
      "precision": null,
      "scale": null,
      "postgresql": {
        "columnName": "date_modified",
        "dataType": "date",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "NO"
      }
    },
    "clientname": {
      "type": "String",
      "required": false,
      "length": null,
      "precision": null,
      "scale": null,
      "postgresql": {
        "columnName": "clientname",
        "dataType": "character",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "YES"
      }
    },
    "password": {
      "type": "String",
      "required": false,
      "length": null,
      "precision": null,
      "scale": null,
      "postgresql": {
        "columnName": "password",
        "dataType": "character",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "YES"
      }
    },
    "company": {
      "type": "String",
      "required": false,
      "length": 255,
      "precision": null,
      "scale": null,
      "postgresql": {
        "columnName": "company",
        "dataType": "character varying",
        "dataLength": 255,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "YES"
      }
    },
    "tokenhash": {
      "type": "String",
      "required": false,
      "length": 255,
      "precision": null,
      "scale": null,
      "postgresql": {
        "columnName": "tokenhash",
        "dataType": "character varying",
        "dataLength": 255,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "YES"
      }
    }
  },
  "tempPassword": {
    "type": "Boolean",
    "required": false,
    "length": null,
    "precision": null,
    "scale": null,
    "postgresql": {
      "columnName": "temp_password",
      "dataType": "boolean",
      "dataLength": null,
      "dataPrecision": null,
      "dataScale": null,
      "nullable": "NO"
    }
  },
  "hidden": ["password", "tokenhash", "tempPassword"],
  "validations": [],
  "relations": {
      "roles": {
          "type": "hasMany",
          "model": "Roles",
          "foreignKey": "userId",
          "through": "RolesUsers"
      },
      "clients": {
          "type": "hasMany",
          "model": "Clients",
          "foreignKey": "userId",
          "through": "ClientsUsers"
      }
  },
  "acls": [],
  "methods": []
}
```

Error:  

```
loopback:connector:postgresql SQL: SELECT "id","type" FROM "public"."roles" WHERE "id"$1 LIMIT 1
Parameters: [2] +31ms
  loopback:connector:postgresql error: syntax error at or near "$1"
    at Connection.parseE (/Users/slively/dev/stitch/node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/slively/dev/stitch/node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/slively/dev/stitch/node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
    at readableAddChunk (_stream_readable.js:168:9)
    at Socket.Readable.push (_stream_readable.js:130:10) +1ms
```

versions:

```
"loopback": "^2.14.0",
    "loopback-boot": "^2.6.5",
    "loopback-connector-postgresql": "^2.3.0",
    "loopback-datasource-juggler": "^2.38.0",
 "loopback-explorer": "^1.7.1",
```

**Comment by yamadapc** [comment]
I've seen this happen multiple times now

**Comment by deepakrkris** [comment]
@slively @yamadapc sorry about the very late response. I am not seeing this issue now. are you still facing this issue ?

**Comment by deepakrkris** [comment]
@yamadapc can you give a brief description of your problem. 
Can you provide a sample for us to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by ssh24** [comment]
This issue should be fixed. Closing this as a result. Feel free to reopen if needed.
