### ISSUE TITLE
TypeError: Object [object Object] has no method 'release'

### ISSUE THREAD

**Issue by elhoyos** [strongloop/loopback-connector-postgresql#109]
I'm having this error when issuing a `SELECT` and then doing a `#rollback` to close the transaction without actually doing other operation. 

```
2015-09-24T18:31:11.750Z pid:2371 worker:36 Thu, 24 Sep 2015 18:31:11 GMT loopback:connector:postgresql SQL: SELECT "field","id" FROM "schema"."table" WHERE "field"=$1 ORDER BY "id"
2015-09-24T18:31:11.750Z pid:2371 worker:36 Parameters: ["foo"]
2015-09-24T18:31:11.750Z pid:2371 worker:36 Thu, 24 Sep 2015 18:31:11 GMT loopback:connector:postgresql Execute SQL within a transaction
2015-09-24T18:31:11.752Z pid:2371 worker:36 events.js:72
2015-09-24T18:31:11.752Z pid:2371 worker:36         throw er; // Unhandled 'error' event
2015-09-24T18:31:11.752Z pid:2371 worker:36               ^
2015-09-24T18:31:11.754Z pid:2371 worker:36 TypeError: Object [object Object] has no method 'release'
2015-09-24T18:31:11.754Z pid:2371 worker:36     at PostgreSQL.releaseConnection (/home/myapp/node_modules/loopback-connector-postgresql/lib/transaction.js:70:14)
2015-09-24T18:31:11.754Z pid:2371 worker:36     at null.<anonymous> (/home/myapp/node_modules/loopback-connector-postgresql/lib/transaction.js:56:12)
2015-09-24T18:31:11.755Z pid:2371 worker:36     at Object.forward (/home/ubuntu/.nvm/v0.10.38/lib/node_modules/strongloop/node_modules/strong-agent/lib/proxy.js:79:23)
2015-09-24T18:31:11.755Z pid:2371 worker:36     at eval (eval at wrap (/home/ubuntu/.nvm/v0.10.38/lib/node_modules/strongloop/node_modules/strong-agent/lib/proxy.js:193:20), <anonymous>:3:21)
2015-09-24T18:31:11.755Z pid:2371 worker:36     at null.<anonymous> (/home/myapp/node_modules/loopback/node_modules/continuation-local-storage/context.js:74:17)
2015-09-24T18:31:11.755Z pid:2371 worker:36     at b [as callback] (domain.js:183:18)
2015-09-24T18:31:11.755Z pid:2371 worker:36     at Query.handleReadyForQuery (/home/myapp/node_modules/loopback-connector-postgresql/node_modules/pg/lib/query.js:89:10)
2015-09-24T18:31:11.755Z pid:2371 worker:36     at null.<anonymous> (/home/myapp/node_modules/loopback-connector-postgresql/node_modules/pg/lib/client.js:163:19)
2015-09-24T18:31:11.755Z pid:2371 worker:36     at emit (events.js:117:20)
2015-09-24T18:31:11.755Z pid:2371 worker:36     at Socket.<anonymous> (/home/myapp/node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:109:12)
```

Please notice this is only happening in production having the same modules version as in development:

```
npm list loopback loopback-datasource-juggler loopback-connector-postgresql
├── loopback@2.22.2
├── loopback-connector-postgresql@2.3.0
└── loopback-datasource-juggler@2.40.1
```

**Comment by raymondfeng** [comment]
Which version of `pg` do you have? Can you check if loopback-connector-postgresql/node_modules/pg/lib/pool.js has the `release` method?

**Comment by elhoyos** [comment]
Running on pg@4.4.2

Here's a strange output:
```
$ npm list pg
└─┬ loopback-connector-postgresql@2.3.0 invalid
  └── pg@4.4.2
```

**Comment by elhoyos** [comment]
The package.json of `loopback-connector-postgresql@2.3.0` says `"pg": "^4.2.0"` and `pg@4.4.2` looks valid for me.

**Comment by elhoyos** [comment]
Please ignore the strange "invalid" output. I was doing it from a different project. The one having the `TypeError` issue looks the same but without the "invalid" string.

**Comment by bajtos** [comment]
@elhoyos could you please create a sample project that we can use to reproduce the problem locally on our machine? See [wiki instructions](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report).

**Comment by timneedham** [comment]
Hi,

**I think this may be a major issue with the latest loopback-connector-postgres?**

```
loopback-connector:            2.3.0
loopback-connector-postgresql: 2.3.0
loopback-datasource-juggler:   2.45.2
pg:                            4.5.2
generic-pool:                  2.1.1
```

For me: running >8 concurrent transactions via `loopback-connector-postgresql` throws `TypeError: pool.release is not a function`.

As requested, @bajtos: I've created a [sample project here](https://github.com/timneedham/loopback-postgres-pool-bug) with steps to reproduce locally.

* @raymondfeng My concern is that under heavy load (using transactions), Loopback will currently fail when using Postgres?

**Comment by Elindorath** [comment]
I can confirm, Loopback is not suitable for production use with Postgres ...

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-connector-postgresql/pull/143

**Comment by Elindorath** [comment]
Glad to hear that! I'll test it as from tomorrow. Thanks a lot!

**Comment by timneedham** [comment]
Great news!

**Comment by robinbiondi** [comment]
Hello, It seems that the upgrade of pg was not resolving the problem. Still have the `pool.release is not a function`.
I made a PR that fixes my issue. PR #146
