### ISSUE TITLE
npm test failing

### ISSUE THREAD

**Issue by ghatwala** [strongloop/loopback-connector-postgresql#114]
Hi All,

When I ran "npm test" on this cloned repo  I got the following errors :+1: 

[root@pts00449-vm19 loopback-connector-postgresql]# npm test

> loopback-connector-postgresql@2.3.0 test /root/strongloop/loopback-connector-postgresql
> mocha -R spec --timeout 10000 --require test/init.js test/*.test.js

  Autocreate schema if not exists
Connection fails:  { [Error: connect ECONNREFUSED 127.0.0.1:5432]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432 }
It will be retried for the next request.
    1) "before all" hook
Connection fails:  { [Error: connect ECONNREFUSED 127.0.0.1:5432]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432 }
It will be retried for the next request.

Connection fails:  [Error: Connection terminated]
It will be retried for the next request.
Connection fails:  [Error: Connection terminated]
It will be retried for the next request.

  0 passing (72ms)
  1 failing

  1) Autocreate schema if not exists "before all" hook:
     Uncaught Error: connect ECONNREFUSED 127.0.0.1:5432
      at Object.exports._errnoException (util.js:837:11)
      at exports._exceptionWithHostPort (util.js:860:20)
      at TCPConnectWrap.afterConnect [as oncomplete](net.js:1060:14)

npm ERR! Test failed.  See above for more details.

Any pointers if anyone has faced the same issue and any possible resolution steps ?

**Comment by superkhau** [comment]
Do you have postgresql installed locally?

**Comment by ghatwala** [comment]
hi @superkhau ,
Thanks , I have now started postgresql running locally as seen below:

[test@pts00449-vm19 loopback-connector-postgresql]$ sudo netstat -tlnp | grep 5432
[sudo] password for test:
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      10726/postgres
tcp6       0      0 ::1:5432                :::*                    LISTEN      10726/postgres

I am now getting the following errors:
/************************************************/


  100) relations hasOne with primaryKey different from model PK should destroy the related item on scope:
     Uncaught AssertionError: expected [Error: Timeout in connecting after 5000 ms] to not exist
      at node_modules/loopback-datasource-juggler/test/relations.test.js:3157:20
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  101) relations hasOne with primaryKey different from model PK should get the related item on scope - verify:
     Uncaught AssertionError: expected [Error: Timeout in connecting after 5000 ms] to not exist
      at node_modules/loopback-datasource-juggler/test/relations.test.js:3168:20
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  102) relations hasMany with primaryKey different from model PK can be used to query employees for boss:
     Uncaught error: Ident authentication failed for user "test"
      at Connection.parseE (node_modules/pg/lib/connection.js:539:11)
      at Connection.parseMessage (node_modules/pg/lib/connection.js:366:17)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:105:22)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)

  103) relations hasMany with primaryKey different from model PK can be used to query employees for boss2:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.


  104) relations belongsTo with primaryKey different from model PK can be used to query data:
     Uncaught error: Ident authentication failed for user "test"
      at Connection.parseE (node_modules/pg/lib/connection.js:539:11)
      at Connection.parseMessage (node_modules/pg/lib/connection.js:366:17)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:105:22)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)

  105) relations hasAndBelongsToMany can be declared:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.


  106) relations hasAndBelongsToMany should allow to create instances on scope:
     Uncaught TypeError: Cannot read property 'tagNames' of undefined
      at node_modules/loopback-datasource-juggler/test/relations.test.js:3288:16
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  107) relations hasAndBelongsToMany should allow to fetch scoped instances:
     Uncaught TypeError: Cannot read property 'tagNames' of undefined
      at node_modules/loopback-datasource-juggler/test/relations.test.js:3302:16
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  108) relations hasAndBelongsToMany should allow to add connection with instance:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.


  109) relations hasAndBelongsToMany should allow to remove connection with instance:
     Uncaught TypeError: Cannot read property 'tagNames' of undefined
      at node_modules/loopback-datasource-juggler/test/relations.test.js:3316:18
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  110) relations hasAndBelongsToMany should allow to create instances on scope with promises:
     Uncaught TypeError: Cannot read property 'tagNames' of undefined
      at node_modules/loopback-datasource-juggler/test/relations.test.js:3330:16
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  111) relations hasAndBelongsToMany should allow to fetch scoped instances with promises:
     Error: Timeout in connecting after 5000 ms
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:10)

  112) relations hasAndBelongsToMany should allow to add connection with instance with promises:
     Error: Timeout in connecting after 5000 ms
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:10)

  113) relations hasAndBelongsToMany should allow to remove connection with instance with promises:
     Error: Timeout in connecting after 5000 ms
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:10)

  114) relations hasAndBelongsToMany should apply inclusion fields to the target model:
     Uncaught AssertionError: expected [Error: Timeout in connecting after 5000 ms] to not exist
      at node_modules/loopback-datasource-juggler/test/relations.test.js:3420:20
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  115) relations hasAndBelongsToMany should apply inclusion where to the target model:
     Uncaught AssertionError: expected [Error: Timeout in connecting after 5000 ms] to not exist
      at node_modules/loopback-datasource-juggler/test/relations.test.js:3445:20
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  116) relations embedsOne can be declared using embedsOne method:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.


  117) relations embedsOne should behave properly without default or being set:
     Uncaught TypeError: Cannot read property 'address' of undefined
      at node_modules/loopback-datasource-juggler/test/relations.test.js:3528:27
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  118) relations embedsOne should create an embedded item on scope:
     Uncaught AssertionError: expected [Error: Timeout in connecting after 5000 ms] to not exist
      at node_modules/loopback-datasource-juggler/test/relations.test.js:3562:20
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  119) relations embedsOne should get an embedded item on scope:
     Uncaught AssertionError: expected [Error: Timeout in connecting after 5000 ms] to not exist
      at node_modules/loopback-datasource-juggler/test/relations.test.js:3575:20
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  120) relations embedsOne should validate an embedded item on scope - on update:
     Uncaught TypeError: Cannot read property 'passportItem' of undefined
      at node_modules/loopback-datasource-juggler/test/relations.test.js:3597:25
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  121) relations embedsOne should update an embedded item on scope:
     Uncaught TypeError: Cannot read property 'passportItem' of undefined
      at node_modules/loopback-datasource-juggler/test/relations.test.js:3611:10
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  122) relations embedsOne should get an embedded item on scope - verify:
     Uncaught AssertionError: expected [Error: Timeout in connecting after 5000 ms] to not exist
      at node_modules/loopback-datasource-juggler/test/relations.test.js:3624:20
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  123) relations embedsOne should destroy an embedded item on scope:
     Uncaught TypeError: Cannot read property 'passportItem' of undefined
      at node_modules/loopback-datasource-juggler/test/relations.test.js:3633:10
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  124) relations embedsOne should get an embedded item on scope - verify:
     Uncaught AssertionError: expected [Error: Timeout in connecting after 5000 ms] to not exist
      at node_modules/loopback-datasource-juggler/test/relations.test.js:3643:20
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  125) relations embedsOne should save an unsaved model:
     Uncaught AssertionError: expected [Error: Timeout in connecting after 5000 ms] to not exist
      at node_modules/loopback-datasource-juggler/test/relations.test.js:3653:20
      at node_modules/loopback-datasource-juggler/lib/relation-definition.js:2116:11
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  126) relations embedsOne should create an embedded item on scope with promises:
     Error: Timeout in connecting after 5000 ms
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:10)

  127) relations embedsOne should get an embedded item on scope with promises:
     Error: Timeout in connecting after 5000 ms
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:10)

  128) relations embedsOne should validate an embedded item on scope with promises - on update:
     Error: Timeout in connecting after 5000 ms
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:10)

  129) relations embedsOne should update an embedded item on scope with promises:
     Error: Timeout in connecting after 5000 ms
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:10)

  130) relations embedsOne should get an embedded item on scope with promises - verify:
     Error: Timeout in connecting after 5000 ms
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:10)

  131) relations embedsOne should destroy an embedded item on scope with promises:
     Error: Timeout in connecting after 5000 ms
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:10)

  132) relations embedsOne should get an embedded item on scope with promises - verify:
     Error: Timeout in connecting after 5000 ms
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:10)

  133) include "before all" hook: setup:
     Uncaught error: Ident authentication failed for user "test"
      at Connection.parseE (node_modules/pg/lib/connection.js:539:11)
      at Connection.parseMessage (node_modules/pg/lib/connection.js:366:17)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:105:22)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)

  134) postgresql connector should run migration:
     Uncaught error: Ident authentication failed for user "test"
      at Connection.parseE (node_modules/pg/lib/connection.js:539:11)
      at Connection.parseMessage (node_modules/pg/lib/connection.js:366:17)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:105:22)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)

  135) postgresql connector should support boolean types with true value:
     Uncaught AssertionError: expected [Error: Timeout in connecting after 5000 ms] to not exist
      at test/postgresql.test.js:36:18
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  136) postgresql connector should support updating boolean types with false value:
     TypeError: Cannot read property 'id' of undefined
      at Context.<anonymous> (test/postgresql.test.js:48:26)

  137) postgresql connector should support boolean types with false value:
     Uncaught AssertionError: expected [Error: Timeout in connecting after 5000 ms] to not exist
      at test/postgresql.test.js:62:18
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  138) postgresql connector should support date types with eq:
     Error: Timeout in connecting after 5000 ms
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:10)

  139) postgresql connector should support date types with between:
     Error: Timeout in connecting after 5000 ms
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:10)

  140) postgresql connector should return the model instance for upsert:
     TypeError: Cannot read property 'id' of undefined
      at Context.<anonymous> (test/postgresql.test.js:96:26)

  141) postgresql connector should return the model instance for upsert when id is not present:
     Uncaught TypeError: Cannot read property 'should' of undefined
      at test/postgresql.test.js:110:12
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  142) postgresql connector should support GeoPoint types:
     Uncaught AssertionError: expected [Error: Timeout in connecting after 5000 ms] to not exist
      at test/postgresql.test.js:162:18
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:7)

  143) postgresql connector regexp operator "before all" hook: deleteTestFixtures for "should support GeoPoint types":
     Error: Timeout in connecting after 5000 ms
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:10)

  144) postgresql connector regexp operator "after all" hook: deleteTestFixtures for "should support GeoPoint types":
     Error: Timeout in connecting after 5000 ms
      at null._onTimeout (node_modules/loopback-datasource-juggler/lib/datasource.js:2116:10)

  145) transactions "before all" hook:
     Uncaught error: Ident authentication failed for user "test"
      at Connection.parseE (node_modules/pg/lib/connection.js:539:11)
      at Connection.parseMessage (node_modules/pg/lib/connection.js:366:17)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:105:22)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)



npm ERR! Test failed.  See above for more details.
/***********************************************/

Any pointers to resolve the above issue ?

**Comment by ghatwala** [comment]
Hi,

Here is the status of the postgresql service status :

[test@pts00449-vm19 loopback-connector-postgresql]$ service postgresql status
Redirecting to /bin/systemctl status  postgresql.service
postgresql.service - PostgreSQL database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql.service; enabled)
   Active: active (running) since Thu 2015-10-29 11:47:06 IST; 2h 22min ago
  Process: 10721 ExecStart=/usr/bin/pg_ctl start -D ${PGDATA} -s -o -p ${PGPORT} -w -t 300 (code=exited, status=0/SUCCESS)
  Process: 10716 ExecStartPre=/usr/bin/postgresql-check-db-dir ${PGDATA} (code=exited, status=0/SUCCESS)
 Main PID: 10726 (postgres)
   CGroup: /system.slice/postgresql.service
           ââ10726 /usr/bin/postgres -D /var/lib/pgsql/data -p 5432
           ââ10727 postgres: logger process
           ââ10729 postgres: checkpointer process
           ââ10730 postgres: writer process
           ââ10731 postgres: wal writer process
           ââ10732 postgres: autovacuum launcher process
           ââ10733 postgres: stats collector process

**Comment by superkhau** [comment]
It is passing 100% on my local clone, but I that's because my settings use a private preconfigured StrongLoop server. When I run it on my local server, I get a bunch of failures too. @raymondfeng Are there any special settings needed to make the tests pass locally?

**Comment by ghatwala** [comment]
Hi @superkhau ,

Can you please let me know your local settings/steps to configure the  private preconfigured strongloop server so that i can see "npm test" commands passing all commands  ,  i am using a red hat enterprise linux virtual machine  (RHEL 7.1 ).

**Comment by superkhau** [comment]
Unfortunately, those settings are for our internal private server so I cannot give it out. I tried installing a local instance of postgres and it fails for me too. This means there are some special settings on our private servers, so we will need to ask @raymondfeng for how to set up a local server to make this pass.

**Comment by ghatwala** [comment]
Hi @superkhau , Thanks for your reply
@raymondfeng Could you please let me the how to set up the local server/steps/setting so that the test cases pass .

**Comment by raymondfeng** [comment]
Please set up the DB with https://github.com/strongloop/loopback-connector-postgresql/blob/master/test/tables.sql

**Comment by ghatwala** [comment]
@raymondfeng - i have run the above script as a "postgres" user.

$ su postgres
bash-4.2$ psql --version
psql (PostgreSQL) 9.2.13
bash-4.2$ psql -f tables.sql  -- > set up the DB using above script.
However when i run $ npm test command i get below:

/*******************/
bash-4.2$ npm test

> loopback-connector-postgresql@2.3.0 test /home/postgres
> mocha -R spec --timeout 10000 --require test/init.js test/*.test.js



  Autocreate schema if not exists
Connection fails:  { [error: Ident authentication failed for user "postgres"]
  name: 'error',
  length: 94,
  severity: 'FATAL',
  code: '28000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '302',
  routine: 'auth_failed' }
It will be retried for the next request.
    1) should run migration for custom schema objects
Connection fails:  [Error: Connection terminated]
It will be retried for the next request.
Connection fails:  { [error: Ident authentication failed for user "postgres"]
  name: 'error',
  length: 94,
  severity: 'FATAL',
  code: '28000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '302',
  routine: 'auth_failed' }
It will be retried for the next request.
    2) should run migration for default schema objects
Connection fails:  { [error: Ident authentication failed for user "postgres"]
  name: 'error',
  length: 94,
  severity: 'FATAL',
  code: '28000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '302',
  routine: 'auth_failed' }
/*******************/

Any pointers on what may be going wrong ?

**Comment by seth-priya** [comment]
Hi,

I have taken over this from @ghatwala 

I could fix the errors mentioned above after changing the postgresql configuration in pg_hba.conf (changed ident to trust).

Now, there are test failures, as follows:
 587 passing (17s)
  21 pending
  4 failing

  1) Discover model primary keys should return an array of primary keys for product:

      Uncaught AssertionError: { owner: 'public',
  tableName: 'product',
  columnName: 'id',
  keySeq: 1,
  pkName: 'product_pkey' } deepEqual { owner: 'strongloop',
  tableName: 'product',
  columnName: 'id',
  keySeq: 1,
  pkName: 'product_pkey' }
      + expected - actual

       {
         "columnName": "id"
         "keySeq": 1
      -  "owner": "public"
      +  "owner": "strongloop"
         "pkName": "product_pkey"
         "tableName": "product"
       }

      at test/postgresql.discover.test.js:120:18
      at Array.forEach (native)
      at test/postgresql.discover.test.js:119:16
      at node_modules/loopback-datasource-juggler/lib/observer.js:166:22
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at PostgreSQL.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:116:5)
      at PostgreSQL.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at cbForWork (node_modules/loopback-datasource-juggler/lib/observer.js:156:14)
      at node_modules/loopback-connector/lib/sql.js:413:7
      at null.callback (lib/postgresql.js:137:7)
      at Query.handleReadyForQuery (node_modules/pg/lib/query.js:89:10)
      at null.<anonymous> (node_modules/pg/lib/client.js:163:19)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:109:12)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)

  2) Discover LDL schema from a table should return an LDL schema for inventory:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.


  3) Discover and build models should build a model from discovery:
     Uncaught TypeError: Cannot read property 'find' of undefined
      at test/postgresql.discover.test.js:203:22
      at node_modules/loopback-datasource-juggler/lib/datasource.js:1615:11
      at node_modules/loopback-datasource-juggler/lib/datasource.js:1308:7
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:396:17
      at done (node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:167:19)
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:40:16
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:393:21
      at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:728:34
      at node_modules/loopback-datasource-juggler/lib/observer.js:166:22
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at PostgreSQL.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:116:5)
      at PostgreSQL.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at cbForWork (node_modules/loopback-datasource-juggler/lib/observer.js:156:14)
      at node_modules/loopback-connector/lib/sql.js:413:7
      at null.callback (lib/postgresql.js:137:7)
      at Query.handleReadyForQuery (node_modules/pg/lib/query.js:89:10)
      at null.<anonymous> (node_modules/pg/lib/client.js:163:19)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:109:12)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)

  4) manipulation updateAttributes should ignore unknown attributes when strict: true:
     error: syntax error at or near "WHERE"
      at Connection.parseE (node_modules/pg/lib/connection.js:539:11)
      at Connection.parseMessage (node_modules/pg/lib/connection.js:366:17)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:105:22)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)



npm ERR! Test failed.  See above for more details.

**Comment by seth-priya** [comment]
With respect to the first failure, owner for product is already strongloop, not sure if any additional configuration is required.
 
strongloop-# \dt product
           List of relations
 Schema |  Name   | Type  |   Owner
--------+---------+-------+------------
 public | product | table | strongloop
(1 row)

strongloop-#

**Comment by dhmlau** [comment]
I've updated the README few weeks ago to include some more information in how to run the tests locally.  Please see if it helps.  If not, feel free to reopen.  Thanks.
