### ISSUE TITLE
discover model indexes causes typeerror

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-connector-postgresql#142]
I'm trying to do some db discovery, and tried to use the discoverModelIndexes function

```
ds.connector.discoverModelIndexes('foo')
```

(where ds is the datasource for the postgress connector)

however, when trying this, I get the error

```js
TypeError: Cannot read property 'settings' of undefined
    at PostgreSQL.Connector.getConnectorSpecificSettings (./node_modules/loopback-connector-postgresql/node_modules/loopback-connector/lib/connector.js:104:52)
    at PostgreSQL.SQLConnector.table (./node_modules/loopback-connector-postgresql/node_modules/loopback-connector/lib/sql.js:116:21)
    at PostgreSQL.getTableStatus (./node_modules/loopback-connector-postgresql/lib/migration.js:47:12)
    at PostgreSQL.discoverModelIndexes (./node_modules/loopback-connector-postgresql/lib/discovery.js:388:10)
```

**Comment by jmls** [comment]
I do find it odd that I have to do a **ds.connector.discover** when all the other methods are on the datasource itself (e.g. **ds.discoverAndBuildModels**)

**Comment by deepakrkris** [comment]
@jmls ds.connector.discoverModelIndexes seems to work fine. the issue could have been related to  model configuration
