### ISSUE TITLE
Version 2.6.0 seems to be a breaking change?

### ISSUE THREAD

**Issue by markstuart** [strongloop/loopback-connector-postgresql#144]
In our project we are specifying `"loopback-connector-postgresql": "^2.4.1"` in our package.json, and this obviously allows this dependency to update as many minor versions as it can on a fresh `npm install`.

Since the 2.6.0 release, I am seeing this error when trying to start the server:
```
/Users/mstuart/src/my-project/node_modules/loopback-connector-postgresql/node_modules/pg/node_modules/pg-pool/index.js:75
        cb(null, client, client.release)
        ^

TypeError: cb is not a function
    at null.<anonymous> (/Users/mstuart/src/my-project/node_modules/loopback-connector-postgresql/node_modules/pg/node_modules/pg-pool/index.js:75:9)
    at Pool.dispense [as _dispense] (/Users/mstuart/src/my-project/node_modules/loopback-connector-postgresql/node_modules/pg/node_modules/pg-pool/node_modules/generic-pool/lib/generic-pool.js:310:14)
    at Pool.release (/Users/mstuart/src/my-project/node_modules/loopback-connector-postgresql/node_modules/pg/node_modules/pg-pool/node_modules/generic-pool/lib/generic-pool.js:429:8)
    at null.<anonymous> (/Users/mstuart/src/my-project/node_modules/loopback-connector-postgresql/node_modules/pg/node_modules/pg-pool/index.js:70:21)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
    at process.fallback (/Users/mstuart/src/my-project/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:450:15)
```

Has the update to pg 6.0.0 changed the way that the loopback-connector-postgresql needs to be used?

*EDIT:* To clarify, this issue goes away if I lock the loopback-connector-postgresql version to 2.4.1

**Comment by markstuart** [comment]
@raymondfeng any ideas why the connector would throw an error when connecting to the db on 2.6.0?

My `datasources.development.js`:
```js
module.exports = {
  db: {
    host: process.env.PG_HOST || 'localhost',
    port: process.env.PG_PORT || 5432,
    database: process.env.PG_DB || '',
    username: process.env.PG_USER || '',
    password: process.env.PG_PASS || '',
    name: process.env.CONNECTOR_NAME || 'db',
    connector: process.env.CONNECTOR || 'memory',
    file: process.env.DATA_FILE
  }
}
```

**Comment by fperks** [comment]
I also have the same issue. Version 2.5.0 seems to work fine however.

**Comment by raymondfeng** [comment]
Do you have a test case for me to reproduce the problem?

Can you print out `cb` at /Users/mstuart/src/my-project/node_modules/loopback-connector-postgresql/node_modules/pg/node_modules/pg-pool/index.js:75 to see what object it is?

**Comment by markstuart** [comment]
It's possible that 2.5.0 works for me also, I haven't tested. Will try to put a test app together today.

**Comment by markstuart** [comment]
Apologies, in my case I am using `connect-pg-simple` for serverside session storage with `express-session`. It appears that this dependency is throwing the error on app boot when trying to connect to the database, not Loopback.

@fperks, I'll close this ticket now, please create a new one if your issue is different or unresolved by the latest `loopback-connector-postgresql` 2.6.3
