### ISSUE TITLE
relation \"public.XXX\" does not exist

### ISSUE THREAD

**Issue by peebles** [strongloop/loopback-connector-postgresql#165]
I did the basics when creating a loopback app.  "yo loopback:datasource" to add postgres and "yo loopback:model" to create a simple model.  But when I run the server and try to access any of the /api endpoints, I am getting:

``` javascript
{
  "error": {
    "name": "error",
    "status": 500,
    "message": "relation \"public.usage\" does not exist",
    "length": 103,
    "severity": "ERROR",
    "code": "42P01",
    "position": "13",
    "file": "parse_relation.c",
    "line": "965",
    "routine": "parserOpenTable",
    "stack": "error: relation \"public.usage\" does not exist\n    at Connection.parseE (/deploy/license-server/node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/deploy/license-server/node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:381:17)\n    at Socket.<anonymous> (/deploy/license-server/node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:117:22)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:153:18)\n    at Socket.Readable.push (_stream_readable.js:111:10)\n    at TCP.onread [as _originalOnread] (net.js:531:20)\n    at TCP.onread (/deploy/license-server/node_modules/loopback/node_modules/loopback-context/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)"
  }
}
```

When I use a mongodb datasource, or mysql, I do not have issues.  I don't know anything about postgres (which is kinda the point with datasources, no?) so I don't know how to proceed.

**Comment by rawrmaan** [comment]
This means that the table `usage` doesn't exist. You can create tables and columns automatically from your Loopback models using autoupdate. See here for more: https://docs.strongloop.com/display/public/LB/Creating+a+database+schema+from+models

**Comment by superkhau** [comment]
Can you provide a sample for us to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by kwiniarski** [comment]
I have got same issue after changing data source from MongoDB to PostgreSQL.
During boot, one of the scripts was responsible for creating default Roles in application. With MongoDB it was enough to do something like this:
```
module.exports = (app, done) => {
  app.models.Role.findOrCreate(...).then(() => done()).catch(done);
}
```
Models where created automatically. With PostgreSQL the code had to be changed slightly to use `autoupdate`:
```
module.exports = (app, done) => {
  app.dataSources.postgresql.autoupdate(() => {
    app.models.Role.findOrCreate(...).then(() => done()).catch(done);
  });
}
```
Is the second example a proper way to write universal boot scripts (data source independent), or is it only PostgreSQL specific?

**Comment by peebles** [comment]
Put a file called "schemaupdate.js" (you can call it anything actually), into server/boot directory with this content:

```javascript
var async = require( 'async' );
module.exports = function( app, cb ) {
  var datasources = Object.keys( app.dataSources );
  async.eachSeries( datasources, function( dsName, cb ) {
    var ds = app.dataSources[ dsName ];
    ds.isActual( function( err, actual ) {
      if ( err ) return cb( err );
      if ( actual ) { console.log( 'datasource', dsName, 'is up to date' ); return cb(); }
      ds.autoupdate( function( err ) {
        if ( err ) return cb( err );
        console.log( 'datasource', dsName, 'updated' );
        cb();
      });
    });
  }, cb );
};
```
and that will handle any datasource, including postgresql.

**Comment by jjhesk** [comment]
i had a similar case see
```
find from table is error ---  { error: relation "people_net.pl_network" does not exist
2017-05-16T22:30:58.830059+00:00 app[web.1]:     at Connection.parseE (/app/node_modules/pg/lib/connection.js:572:11)
2017-05-16T22:30:58.830060+00:00 app[web.1]:     at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:396:17)
2017-05-16T22:30:58.830060+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:132:22)
2017-05-16T22:30:58.830062+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-05-16T22:30:58.830062+00:00 app[web.1]:     at Socket.emit (events.js:188:7)
2017-05-16T22:30:58.830064+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:176:18)
2017-05-16T22:30:58.830064+00:00 app[web.1]:     at Socket.Readable.push (_stream_readable.js:134:10)
2017-05-16T22:30:58.830065+00:00 app[web.1]:     at TCP.onread (net.js:551:20)
2017-05-16T22:30:58.830066+00:00 app[web.1]:   name: 'error',
2017-05-16T22:30:58.830068+00:00 app[web.1]:   length: 120,
2017-05-16T22:30:58.830069+00:00 app[web.1]:   severity: 'ERROR',
2017-05-16T22:30:58.830069+00:00 app[web.1]:   code: '42P01',
2017-05-16T22:30:58.830070+00:00 app[web.1]:   detail: undefined,
2017-05-16T22:30:58.830070+00:00 app[web.1]:   hint: undefined,
2017-05-16T22:30:58.830071+00:00 app[web.1]:   position: '88',
2017-05-16T22:30:58.830071+00:00 app[web.1]:   internalPosition: undefined,
2017-05-16T22:30:58.830072+00:00 app[web.1]:   internalQuery: undefined,
2017-05-16T22:30:58.830073+00:00 app[web.1]:   where: undefined,
2017-05-16T22:30:58.830073+00:00 app[web.1]:   schema: undefined,
2017-05-16T22:30:58.830074+00:00 app[web.1]:   table: undefined,
2017-05-16T22:30:58.830074+00:00 app[web.1]:   column: undefined,
2017-05-16T22:30:58.830075+00:00 app[web.1]:   dataType: undefined,
2017-05-16T22:30:58.830075+00:00 app[web.1]:   constraint: undefined,
2017-05-16T22:30:58.830075+00:00 app[web.1]:   file: 'parse_relation.c',
2017-05-16T22:30:58.830076+00:00 app[web.1]:   line: '1138',
2017-05-16T22:30:58.830077+00:00 app[web.1]:   routine: 'parserOpenTable' }

```

**Comment by necevil** [comment]
I had this issue when moving to Postgres as well.
Doing auto-update on my models with a boot script as mentioned by @kwiniarski and @peebles did the trick.

**Comment by abdulwahid24** [comment]
@peebles Tons of thanks to you. I would love to have this functionality builtin.

**Comment by ssh24** [comment]
The original question of the issue has been solved. You need to `autoupdate`/`automigrate` your models before performing CRUD operations on a fresh model you created in your loopback app. 

Closing this issue as resolved. Feel free to reopen if needed.

**Comment by kareemhossam** [comment]
I have the same error, only difference is that The models that have this error are ones that were discovered from DB schemas, I used the loopback-discovery cli to get these models and i know that these models do not belong in the public schema, my question is how to change this, its schema is specified in the models' JSON file
