### ISSUE TITLE
Case insensitive pattern matching for postgresql connector

### ISSUE THREAD

**Issue by timlind** [strongloop/loopback-connector-postgresql#188]
Currently doing a find with `{ where: { property: { ilike: "keyword" }}}` results in a sql syntax error on the postgresql connector.

**Comment by aymanm** [comment]
Use a work around:
{"where": {"property": {"regexp": "/keyword/i"}}}

**Comment by ssh24** [comment]
You can use `ilike` and `nlike` properties in postgres connector.

Here is a sample code snippet:

**model-definition.json**
```json
{
  "name": "Post",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "title": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var util = require('util');
var _ = require('lodash');

module.exports = function(app) {
    var db = app.datasources.postgresqlDs;
    var Post = app.models.Post;

    db.automigrate(function(err) {
        if (err) throw err;
        console.log('\nAutomigrate completed');

        Post.create([{
            title: 'AAA',
        }, {
            title: 'aaa'
        }, {
            title: 'BBB'
        }, {
            title: 'bbb'
        }], function(err, result) {
            if (err) throw err;
            console.log('\nCreated instance: ' + util.inspect(result));

            Post.find({where: {title: {ilike: 'a%'}}}, function(err, result) {
                if (err) throw err;
                console.log('\nFound instance with ilike: ' + util.inspect(result));

                Post.find({where: {title: {nilike: 'a%'}}}, function(err, result) {
                    if (err) throw err;
                    console.log('\nFound instance with nilike: ' + util.inspect(result));
                });
            });
        });
    });
};
```

**output**
```bash
sakibs-mac:postgresql-188 ssh$ node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer

Automigrate completed

Created instance: [ { title: 'AAA', id: 1 },
  { title: 'aaa', id: 2 },
  { title: 'BBB', id: 3 },
  { title: 'bbb', id: 4 } ]

Found instance with ilike: [ { title: 'AAA', id: 1 }, { title: 'aaa', id: 2 } ]

Found instance with nilike: [ { title: 'BBB', id: 3 }, { title: 'bbb', id: 4 } ]
```

Closing this story as a result. Feel free to reopen if needed.

**Comment by ZeeAzmat** [comment]
Tried this, but it isn't working. Still getting the same error

**Comment by ZeeAzmat** [comment]
Here is the code snippet. Any help would be appreciated.
`
    User.find({where: {firstName: {ilike: 'zee%'}}}, function(err, result) {
      if (err) throw err;
      console.log('Found instance with ilike: ', result);
    });
`

**Comment by osazemeu** [comment]
Same here.

```
{
  "error": {
    "statusCode": 500,
    "name": "error",
    "message": "syntax error at or near \"$1\"",
    "length": 92,
    "severity": "ERROR",
    "code": "42601",
    "position": "115",
    "file": "scan.l",
    "line": "1087",
    "routine": "scanner_yyerror",
    "stack": "error: syntax error at or near \"$1\"\n    at Connection.parseE (/var/app/current/node_modules/pg/lib/connection.js:545:11)\n    at Connection.parseMessage (/var/app/current/node_modules/pg/lib/connection.js:370:19)\n    at Socket.<anonymous> (/var/app/current/node_modules/pg/lib/connection.js:113:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (stream_readable.js:263:12)\n    at readableAddChunk (stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:594:20)"
  }
}
```
