### ISSUE TITLE
[BUG] Unknown Syntax Error

### ISSUE THREAD

**Issue by DerekTBrown** [strongloop/loopback-connector-postgresql#263]
Here is my findOne (inside of a validateAsync function):
```
Reservation.findOne({
              where: {
                and : [

                  {id : {neq: instance.id}},

                  // Same Machine
                  {device: instance.device},

                  // Active or Pending Reservation
                  {status: {neq: "ended"}},

                  // Time Interval Overlap
                  {or : [
                    {and: [
                      {time_start : {lt: instance.time_start}},
                      {time_end : {gt: instance.time_start}}
                    ]},
                    {and: [
                      {time_start : {lt: instance.time_end}},
                      {time_end : {gt: instance.time_start}}
                    ]}
                  ]}
                ]
              }
          }, function(err, conflict){
                if(err){
                  Reservation.app.log.warn("Reservation validation error",err);
                  invalid();
                } else if(conflict){
                  invalid();
                } else {
                  resolve();
                }
          });
```

Here is the error it produces:
```
vallidation error error: syntax error at or near "DEFAULT"
    at Connection.parseE (/Users/derekbrown/Projects/PocketFlint 3/pocketflint/src/node_modules/pg/lib/connection.js:572:11)
    at Connection.parseMessage (/Users/derekbrown/Projects/PocketFlint 3/pocketflint/src/node_modules/pg/lib/connection.js:396:17)
    at Socket.<anonymous> (/Users/derekbrown/Projects/PocketFlint 3/pocketflint/src/node_modules/pg/lib/connection.js:132:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
```

**Comment by DerekTBrown** [comment]
Here is the SQL Query:
```sql
ERROR:  syntax error at or near "DEFAULT" at character 94
STATEMENT:  SELECT "id","device","time_start","time_end","status" FROM "public"."reservation" WHERE ("id"DEFAULT) AND ("device"=$1) AND ("status"!=$2) AND ((("time_start"<$3::TIMESTAMP WITH TIME ZONE) AND ("time_end">$4::TIMESTAMP WITH TIME ZONE)) OR (("time_start"<$5::TIMESTAMP WITH TIME ZONE) AND ("time_end">$6::TIMESTAMP WITH TIME ZONE))) ORDER BY "id" LIMIT 1
```

**Comment by DerekTBrown** [comment]
Solved: problem was that the "id" value was undefined, which caused an invalid query.  Probably should throw some type of error to avoid debugging this in the future?

**Comment by ssh24** [comment]
The error thrown is quite straight forward. It is up to the user to validate that whatever `id` is being passed is a **correct** id value. If in the case, they fail to validate it, the error is caught upon the stderr from the database itself. 

In this case, looks like `instance.id` is undefined and that is why it was failing.
```
{id : {neq: instance.id}},
```
