### ISSUE TITLE
migration broken with 3.0.1

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-connector-postgresql#267]
# Description/Steps to reproduce
run a migration on a table that has this definition
```
"properties": {
    "id": {
      "type": "number",
      "id": true,
      "generated": true,
      "postgresql": {
        "dataType": "serial",
        "nullable": "NO"
      }
    },
```
# Expected result
no errors ... the same migration *does not* cause this error, it completes successfully

# Additional information
the error encountered is
```
{ error: type "serial" does not exist
    at Connection.parseE (node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:250:12)
    at readableAddChunk (_stream_readable.js:237:11)
    at Socket.Readable.push (_stream_readable.js:195:10)
    at TCP.onread (net.js:586:20)
  name: 'error',
  length: 89,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_type.c',
  line: '257',
  routine: 'typenameType' }

```

**Comment by ssh24** [comment]
The **generated** flag triggers `SERIAL` type. You do not need to specify the explicit datatype again.

```json
    "id": {
      "type": "number",
      "id": true,
      "required": true,
      "generated": true
    }
```
