### ISSUE TITLE
Fatal Error:  connector crashes loopback on [where][date]='invalid date format' api query

### ISSUE THREAD

**Issue by sentientnebula** [strongloop/loopback-connector-postgresql#37]
This is a show stopper. If it doesn't like the date format, it crashes the whole API.  Can't use this in production.

/var/www/html/api/node_modules/loopback-connector-postgresql/lib/postgresql.js:542
    var iso = escape(val.toISOString());
                         ^
RangeError: Invalid time value
    at Date.toISOString (native)
    at PostgreSQL.toDatabase (/var/www/html/api/node_modules/loopback-connector-postgresql/lib/postgresql.js:542:26)
    at /var/www/html/api/node_modules/loopback-connector-postgresql/lib/postgresql.js:797:32
    at Array.forEach (native)
    at PostgreSQL._buildWhere (/var/www/html/api/node_modules/loopback-connector-postgresql/lib/postgresql.js:769:24)
    at PostgreSQL.buildWhere (/var/www/html/api/node_modules/loopback-connector-postgresql/lib/postgresql.js:745:20)
    at PostgreSQL.toFilter (/var/www/html/api/node_modules/loopback-connector-postgresql/lib/postgresql.js:872:20)
    at PostgreSQL.all (/var/www/html/api/node_modules/loopback-connector-postgresql/lib/postgresql.js:707:12)
    at Function.find (/var/www/html/api/node_modules/loopback-datasource-juggler/lib/dao.js:790:34)
    at SharedMethod.invoke (/var/www/html/api/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:224:17)

**Comment by davidcheung** [comment]
Closing out old issues, looks like issue was addressed thru https://github.com/strongloop/strong-remoting/pull/119
