### ISSUE TITLE
Complex order statement fails 

### ISSUE THREAD

**Issue by JuergenSimon** [strongloop/loopback-connector-postgresql#435]
#355  Steps to reproduce

We have a table that has fields weight (float) and voterId (integer, foreign key). We would like to sort the results of a query in the following way:  

filter.order=["(weight/GREATEST(ABS(weight), 1)) DESC", "voterId ASC", "ABS(weight) DESC"]

## Current Behavior

The query breaks with the following error:

```
error: column "(weight/greatest(abs(weight)" does not exist
    at Connection.parseE (.../node_modules/pg/lib/connection.js:581:48)
    at Connection.parseMessage (.../node_modules/pg/lib/connection.js:380:19)
    at Socket.<anonymous> (.../node_modules/pg/lib/connection.js:116:22)
```

## Expected Behavior

The results are ordered as according to the statement that should be generated. 

## Additional information

This issue cropped up in 5.x versions of the connector. Perhaps it has something to do with the upgrade of pg?

**Comment by JuergenSimon** [comment]
ADDENDUM: Downgrading to 3.8.3 fixed the problem. 3.9.x exhibited it as well.

**Comment by JuergenSimon** [comment]
I would like to escalate this a little. The reason is, that I'm in a bind now. My old (high sierra) iMac died last week. It seems on Catalina, the 3.8.3 connector is no longer working at all (connection timeouts). This means I can only connect using the 5.0.1 connector, which exposes the bug described in this ticket.

**Comment by JuergenSimon** [comment]
The issue unfortunately prevails.

**Comment by JuergenSimon** [comment]
Is there a way to escalate this ticket? We're really stuck here.

**Comment by JuergenSimon** [comment]
I can report that this error was fixed but only when also using the latest version of `loopback-connector`.
