### ISSUE TITLE
LB4 with  loopback-connector-postgresql@5.3.0

### ISSUE THREAD

**Issue by KevinChengYang** [strongloop/loopback-connector-postgresql#476]
I kept getting the same error in LB4 even using the right syntax below and right version of loopback-connector-postgresql@5.3.0 after I deploy it to IBM Cloud Kubenetes, it runs without any issues on my local.

import {BootMixin} from '@loopback/boot';
import {ApplicationConfig} from '@loopback/core';
import {RepositoryMixin} from '@loopback/repository';
import {RestApplication} from '@loopback/rest';
import {
  RestExplorerBindings,
  RestExplorerComponent
} from '@loopback/rest-explorer';
import {ServiceMixin} from '@loopback/service-proxy';
import fs from 'fs';
import path from 'path';
import {ProductSelectionDataSource} from './datasources';
import {MySequence} from './sequence';
export {ApplicationConfig};

export class ProductSelectionApplication extends BootMixin(
  ServiceMixin(RepositoryMixin(RestApplication)),
) {
  constructor(options: ApplicationConfig = {}) {
    super(options);

    //process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';
    console.log("__dirname: " + __dirname);
    console.log("*********************************************************************************");
    const crtpath = path.join(__dirname, '../private/ca.crt');
    console.log("crtpath:" + crtpath);
    console.log("content of crt:  " + fs.readFileSync(crtpath).toString());

    console.log("*********************************************************************************");
    const keypath = path.join(__dirname, '../private/ca.key');
    console.log("keypath:" + keypath);
    console.log("content of key:  " + fs.readFileSync(keypath).toString());

    console.log("*********************************************************************************");
    var dbcert = process.env.DB_CERT;
    let dbCert = Buffer.from(`{dbcert}`, 'base64');
    console.log("content of dbcert: " + dbCert);

    console.log("*********************************************************************************");

    this.bind('datasources.config.productSelection').to({
      name: 'dbname',
      connector: 'postgresql',
      url: process.env.DB_CONNECTION_STRING,
      ssl: {
        ca: fs.readFileSync(crtpath).toString(),
        key: fs.readFileSync(keypath).toString(),
        cert: dbCert,
        rejectUnauthorized: false,
      },
    });
    this.bind('datasources.productSelection').toClass(ProductSelectionDataSource);

    // Set up the custom sequence
    this.sequence(MySequence);

    // Set up default home page
    this.static('/', path.join(__dirname, '../public'));

    // Customize @loopback/rest-explorer configuration here
    this.configure(RestExplorerBindings.COMPONENT).to({
      path: '/explorer',
    });
    this.component(RestExplorerComponent);

    this.projectRoot = __dirname;
    // Customize @loopback/boot Booter Conventions here
    this.bootOptions = {
      controllers: {
        // Customize ControllerBooter Conventions here
        dirs: ['controllers'],
        extensions: ['.controller.js'],
        nested: true,
      },
    };
  }
}

The error I got:

Node ENV: dev
Server is running at http://127.0.0.1:3000
Try http://127.0.0.1:3000/ping
Connection fails: Error: self signed certificate in certificate chain
It will be retried for the next request.
_tls_wrap.js:1497

Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:131:14)

   
I tried to use old version of  loopback-connector-postgresql@3.9.1 but it seems the latest version of LB4 doesn't like it.

Please advise and thank you so much.

**Comment by dhmlau** [comment]
Cross posting the answer from @raymondfeng on Slack: https://loopbackio.slack.com/archives/C01177XQN8N/p1617727228152000.

> For TLS self-signed, there should be a connector setting that you can set to skip that
> Check the pg npm package to find out what option to set
> We pass connector settings to the underlying driver

**Comment by dhmlau** [comment]
@KevinChengYang, are you good with closing this issue? Thanks.

**Comment by KevinChengYang** [comment]
Hi Diana,

Disable TLS warning will compromise the security of this service, I can do that for dev environment, but it's absolutely not acceptable for Production environment.

(node:1) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

This defect need to be fixed as soon as possible.

Thank you.

**Comment by kwokgordon** [comment]
Hi Diana,

I am experiencing the same issue as Kevin.  Do you have an ETA when this issue will be fixed?

Thank you.
