### ISSUE TITLE
ReferencesMany and "inq" filter on id result in error

### ISSUE THREAD

**Issue by bkniffler** [strongloop/loopback-connector-postgresql#70]
Hey, 
I set up a referencesMany relation between objects, now when I run something like this:
```
http://localhost:3010/api/Entries?filter={"where":{"tagIds":{"inq":[2]}}}
```
I get the following error
```
{"error":{"name":"error","status":500,"message":"operator does not exist: character varying = integer","length":208,"severity":"ERROR","code":"42883","hint":"No operator matches the given name and argument type(s). You might need to add explicit type casts.","position":"196","file":"parse_oper.c","line":"722","routine":"op_error","stack":"error: operator does not exist: character varying = integer\n    
at Connection.parseE (.../node_modules/pg/lib/connection.js:534:11)\n    
at Connection.parseMessage (.../node_modules/pg/lib/connection.js:361:17)\n    
at Socket.<anonymous> (.../node_modules/pg/lib/connection.js:105:22)\n    
at emitOne (events.js:75:13)\n    
at Socket.emit (events.js:150:7)\n    
at readableAddChunk (_stream_readable.js:146:16)\n    
at Socket.Readable.push (_stream_readable.js:109:10)\n    
at TCP.onread (net.js:510:20)"}}
```

```
Entry.json
{
  "name": "Entry",
  "plural": "Entries",
  "base": "PersistedModel",
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
  },
  "relations": {
    "tags": {
      "type": "referencesMany",
      "model": "Tag"
    }
  }
}
```

```
Tag.json
{
  "name": "Tag",
  "plural": "Tags",
  "base": "PersistedModel",
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "relations": {
    "entries": {
      "type": "hasAndBelongsToMany",
      "model": "Entry"
    }
  }
}
```

Am I missing something or is this a bug?

**Comment by bkniffler** [comment]
Well, I guess I missed the point that its supposed to work the other way around. What I'm trying to achieve is currently not possible, I think I'd need JSON field types to run "contains" operations on arrays.
