### ISSUE TITLE
Error with dates

### ISSUE THREAD

**Issue by kesavkolla** [strongloop/loopback-connector-postgresql#81]
I've a database with column type date

```
   Column   |  Type   | Modifiers
------------+---------+-----------
 property   | uuid    |
 staydate   | date    |
 totrevenue | numeric |
```

I created model to reflect this table:

```
"properties": {
		"property": {
			"type": "string",
			"id": true,
			"required": true,
			"postgresql": {
				"dataType": "uuid"
			}
		},
		"staydate": {
			"type": "date",
			"required": true
		}
}
```

When I do query for staydate:

app.models.Histrollup.find({where: {property: '992ab64e-e15b-11e4-9319-c39ff206d9ab', staydate: {between: [Date.create('2015-05-01'), Date.create('2015-05-10')]}}}, function(err,data){})

Here is the debug log:
```
loopback:connector:postgresql SQL: SELECT "property","staydate","rolluptype","totnights","totrevenue","bymarketcd","bychannel","byroomtype" FROM "castle"."v_histrollup" WHERE "property"=$1 AND "staydate" BETWEEN $2 AND $3 ORDER BY "property"
Parameters: ["992ab64e-e15b-11e4-9319-c39ff206d9ab",{"sql":"to_timestamp(?,'yyyy-mm-dd hh24:mi:ss.ms')","params":["2015-05-01T10:00:00.000Z"]},{"sql":"to_timestamp(?,'yyyy-mm-dd hh24:mi:ss.ms')","params":["2015-05-10T10:00:00.000Z"]}] +1m
undefined
>   loopback:connector:postgresql error: invalid input syntax for type date: "{"sql":"to_timestamp(?,'yyyy-mm-dd hh24:mi:ss.ms')","params":["2015-05-01T10:00:00.000Z"]}"
    at Connection.parseE (/Users/kesav/Programming/projects/hotelsoft/hotelsoftrzr/node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/Users/kesav/Programming/projects/hotelsoft/hotelsoftrzr/node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/Users/kesav/Programming/projects/hotelsoft/hotelsoftrzr/node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:145:16)
    at Socket.Readable.push (_stream_readable.js:109:10)
    at TCP.onread (net.js:521:20) +10ms
```

The parameter **{"sql":"to_timestamp(?,'yyyy-mm-dd hh24:mi:ss.ms')** is not valid for dates

**Comment by kesavkolla** [comment]
I didn't pull the latest branch.
