### ISSUE TITLE
find / find all throws error -> has no method 'notifyObserversAround

### ISSUE THREAD

**Issue by raghava** [strongloop/loopback-connector-postgresql#83]
Through API explorer, if I choose 'find' or 'findAll' I'm seeing the following error. By the way If I choose the loopback-connector@2.1.2 It works fine. 

Package version
```
loopback-datasource-juggler@2.28.0
loopback-connector-postgresql@2.1.0
loopback-connector@2.2.1
```

Response Body
```json
{
  "error": {
    "name": "TypeError",
    "status": 500,
    "message": "Object #<PostgreSQL> has no method 'notifyObserversAround',
    "stack": "TypeError: Object #<PostgreSQL> has no method 'notifyObserversAround'\n    at PostgreSQL.SQLConnector.execute (/home/ec2-user/pocketnews/node_modules/loopback-connector-postgresql/node_modules/loopback-connector/lib/sql.js:407:8)\n    at PostgreSQL.find [as all] (/home/ec2-user/pocketnews/node_modules/loopback-connector-postgresql/node_modules/loopback-connector/lib/sql.js:1050:8)\n    at /home/ec2-user/pocketnews/node_modules/loopback-datasource-juggler/lib/dao.js:1362:19\n    at doNotify (/home/ec2-user/pocketnews/node_modules/loopback-datasource-juggler/lib/observer.js:74:49)\n    at doNotify (/home/ec2-user/pocketnews/node_modules/loopback-datasource-juggler/lib/observer.js:74:49)\n    at doNotify (/home/ec2-user/pocketnews/node_modules/loopback-datasource-juggler/lib/observer.js:74:49)\n    at doNotify (/home/ec2-user/pocketnews/node_modules/loopback-datasource-juggler/lib/observer.js:74:49)\n    at Function.ObserverMixin._notifyBaseObservers (/home/ec2-user/pocketnews/node_modules/loopback-datasource-juggler/lib/observer.js:97:5)\n    at Function.ObserverMixin.notifyObserversOf (/home/ec2-user/pocketnews/node_modules/loopback-datasource-juggler/lib/observer.js:72:8)\n    at Function.ObserverMixin._notifyBaseObservers (/home/ec2-user/pocketnews/node_modules/loopback-datasource-juggler/lib/observer.js:95:15)"
  }
}
```

In Console Error
```
/home/app/node_modules/loopback-connector-postgresql/node_modules/loopback-connector/lib/sql.js:407
  this.notifyObserversAround('execute', context, function(context, done) {
       ^
TypeError: Object #<PostgreSQL> has no method 'notifyObserversAround'
    at PostgreSQL.SQLConnector.execute (/home/app/node_modules/loopback-connector-postgresql/node_modules/loopback-connector/lib/sql.js:407:8)
    at PostgreSQL.find [as all] (/home/app/node_modules/loopback-connector-postgresql/node_modules/loopback-connector/lib/sql.js:1050:8)
    at /home/app/node_modules/loopback-datasource-juggler/lib/dao.js:1362:19
    at doNotify (/home/app/node_modules/loopback-datasource-juggler/lib/observer.js:74:49)
    at doNotify (/home/app/node_modules/loopback-datasource-juggler/lib/observer.js:74:49)
    at doNotify (/home/app/node_modules/loopback-datasource-juggler/lib/observer.js:74:49)
    at doNotify (/home/app/node_modules/loopback-datasource-juggler/lib/observer.js:74:49)
    at Function.ObserverMixin._notifyBaseObservers (/home/app/node_modules/loopback-datasource-juggler/lib/observer.js:97:5)
    at Function.ObserverMixin.notifyObserversOf (/home/app/node_modules/loopback-datasource-juggler/lib/observer.js:72:8)
    at Function.ObserverMixin._notifyBaseObservers (/home/app/node_modules/loopback-datasource-juggler/lib/observer.js:95:15)
```

**Comment by raymondfeng** [comment]
Please run 'npm up' to upgrade the loopback-datasource-juggler dep.
