### ISSUE TITLE
Function `now` is not executed  [BUG]

### ISSUE THREAD

**Issue by vladmiller** [strongloop/loopback-connector-postgresql#85]
Function `now` is not getting executed

```javascript
"properties": {
  "created": {
      "type": "date",
      "default": "now"
    }
}
```

In line 450, variable val should already have current timestamp, instead it will have `Invalid Date` error.

```
/Users/vladmiller/Projects/kiidu/kiidu/node_modules/loopback-connector-postgresql/lib/postgresql.js:450
    var iso = val.toISOString();
                  ^
RangeError: Invalid time value
    at Date.toISOString (native)
    at PostgreSQL.toColumnValue (/Users/vladmiller/Projects/kiidu/kiidu/node_modules/loopback-connector-postgresql/lib/postgresql.js:453:19)
    at PostgreSQL.SQLConnector.buildFields (/Users/vladmiller/Projects/kiidu/kiidu/node_modules/loopback-connector-postgresql/node_modules/loopback-connector/lib/sql.js:888:18)
    at PostgreSQL.SQLConnector.buildInsert (/Users/vladmiller/Projects/kiidu/kiidu/node_modules/loopback-connector-postgresql/node_modules/loopback-connector/lib/sql.js:349:21)
    at PostgreSQL.SQLConnector.create (/Users/vladmiller/Projects/kiidu/kiidu/node_modules/loopback-connector-postgresql/node_modules/loopback-connector/lib/sql.js:428:19)
    at ModelConstructor.<anonymous> (/Users/vladmiller/Projects/kiidu/kiidu/node_modules/loopback-datasource-juggler/lib/dao.js:308:21)
    at ModelConstructor.trigger (/Users/vladmiller/Projects/kiidu/kiidu/node_modules/loopback-datasource-juggler/lib/hooks.js:65:12)
    at ModelConstructor.<anonymous> (/Users/vladmiller/Projects/kiidu/kiidu/node_modules/loopback-datasource-juggler/lib/dao.js:271:11)
    at ModelConstructor.trigger (/Users/vladmiller/Projects/kiidu/kiidu/node_modules/loopback-datasource-juggler/lib/hooks.js:65:12)
    at create (/Users/vladmiller/Projects/kiidu/kiidu/node_modules/loopback-datasource-juggler/lib/dao.js:270:9)
```

**Comment by raymondfeng** [comment]
`default` should be `defaultFn` in your case.

**Comment by vladmiller** [comment]
This is very weird, because ```default``` worked in the past.
